---
title: "HUMAN POST-IMPLANTATION DEVELOPMENT IN VITRO BY DE NOVO EMBRYONIC AND EXTRA-EMBRYONIC LINEAGE PATTERNING"
author: "Nicolas Dias"
---

```{r Figure 2A_1}
require(Seurat)
require(ggplot2)

data <- readRDS("hee_seurat.rds") 

cluster_colors <- c("#85C1E9", "#B03A2E", "#F1948A", "#AF7AC5", "#F5B041", "#808B96", "#2471A3", "#229954")
cluster_order <- c("PI-Epi", "AME", "NNE", "PS-like", "Mesoderm-like", "G1 Hypoblast", "G2M/S Hypoblast", "AVE-like")

annotation <- data.frame(colors = cluster_colors, order = cluster_order)

DimPlot(data) + scale_color_manual(values = as.character(annotation$colors), breaks = annotation$order)
```

```{r Figure 2A_2}
require(Seurat)
require(ComplexHeatmap)
require(presto)
require(stringr)
require(circlize)
require(viridis)

data <- readRDS("hee_seurat.rds") 

cluster_colors <- c("#85C1E9", "#B03A2E", "#F1948A", "#AF7AC5", "#F5B041", "#808B96", "#2471A3", "#229954")
cluster_order <- c("PI-Epi", "AME", "NNE", "PS-like", "Mesoderm-like", "G1 Hypoblast", "G2M/S Hypoblast", "AVE-like")

annotation <- data.frame(colors = cluster_colors, order = cluster_order)

markers <- wilcoxauc(data, 'Cell.type', assay = 'data')
sig_markers <- markers[markers$padj < 0.01, ]
sig_markers <- sig_markers[order(sig_markers$group),]
sig_markers$group <- str_replace(sig_markers$group, "/", "_")

top_markers <- top_markers(sig_markers, n = 100, auc_min = 0.5, pct_in_min = 20, pct_out_max = 20)
genes <- unique(as.vector(as.matrix(top_markers[1:20, str_replace(annotation$order, "/", "_")])))

mat <- AverageExpression(data, assays = "RNA", features = genes, group.by = "Cell.type")$RNA
mat <- t(scale(t(mat[,annotation$order])))
cluster_anno <- factor(annotation$order, levels = annotation$order)

col_fun = colorRamp2(c(-1, 0, 2.5), viridis(3))

ht <- Heatmap(mat, name = "Expression",  
        column_split = factor(cluster_anno, levels = annotation$order),
        cluster_columns = FALSE,
        show_column_dend = FALSE,
        cluster_column_slices = FALSE,
        column_title_gp = gpar(fontsize = 8),
        column_gap = unit(0.8, "mm"),
        cluster_rows = FALSE,
        show_row_dend = FALSE,
        col = col_fun,
        row_names_gp = gpar(fontsize = 6),
        column_title_rot = 90,
        top_annotation = HeatmapAnnotation(foo = anno_block(gp = gpar(fill = annotation$colors))),
        show_column_names = FALSE,
        use_raster = TRUE,
        raster_quality = 10,
        show_heatmap_legend = TRUE,
        show_row_names = FALSE)


fig_2b <- draw(ht)
fig_2b 
```

```{r Figure 2C}
require(Seurat)
require(pheatmap)
require(SingleCellExperiment)
require(Matrix.utils)
require(DESeq2)
require(dplyr)
require(purrr)

data <- readRDS("hee_seurat.rds") 
xiang <- readRDS("xiang_seurat.rds")
tyser <- readRDS("tyser_seurat.rds")

tyser$cell.type <- paste0("Tyser_", tyser$cell.type)
xiang$Cell_type <- paste0("Xiang_", xiang$Cell_type)

genes <- intersect(intersect(rownames(data),rownames(tyser)), rownames(xiang))

merged_data <- merge(data, c(tyser, xiang))
counts <- merged_data[["RNA"]]@counts[genes, ] %>% as.matrix()

md <- merged_data@meta.data
md <- md %>%
   mutate(Type = coalesce(Cell_type, cell.type, Cell.type))
md$orig.ident[is.na(md$orig.ident)] <- "hEE"

md$sample_id <- factor(md$Type)
md$group_id <- factor(md$orig.ident)
md <- md[, c("group_id", "sample_id")]

sce <- SingleCellExperiment(assays = list(counts = counts), 
                           colData = md)

n_cells <- as.numeric(table(sce$sample_id))
sids <- set_names(levels(sce$sample_id))
m <- match(sids, sce$sample_id)

ei <- data.frame(colData(sce)[m, ], 
                  n_cells, row.names = NULL)

metadata <- ei %>% select(-"n_cells")
rownames(metadata) <- metadata$sample_id

groups <- colData(sce)[, "sample_id"]
pb <- aggregate.Matrix(t(counts(sce)), 
                       groupings = groups, fun = "sum")
counts <- t(pb)


dds <- DESeqDataSetFromMatrix(round(counts), 
                              colData = metadata, 
                              design = ~ group_id)

rld <- vst(dds, blind=TRUE)
rld_mat <- assay(rld)
rld_cor <- cor(rld_mat)
cor_data <- rld_cor[order(annotation$order), setdiff(rownames(rld_cor), annotation$order)]

d1 <- t(scale(t(rld_cor[order(annotation$order), rownames(rld_cor)[grep("Tyser", rownames(rld_cor))]])))
d2 <- t(scale(t(rld_cor[order(annotation$order), rownames(rld_cor)[grep("Xiang", rownames(rld_cor))]])))
d <- cbind(d1, d2)

pheatmap(t(scale(t(d))), annotation = metadata[, c("group_id"), drop=F])
```

```{r Figure 2D}
require(Seurat)
require(ggplot2)
require(scales)

data <- readRDS("hee_seurat.rds") 

cluster_colors <- c("#85C1E9", "#B03A2E", "#F1948A", "#AF7AC5", "#F5B041", "#808B96", "#2471A3", "#229954")
cluster_order <- c("PI-Epi", "AME", "NNE", "PS-like", "Mesoderm-like", "G1 Hypoblast", "G2M/S Hypoblast", "AVE-like")

annotation <- data.frame(colors = cluster_colors, order = cluster_order)

data <- AddModuleScore(data, features = list(c("CD48", "PTN", "KIT", "EGF")), name = "DE_markers")
data <- AddModuleScore(data, features = list(c("APOC1", "PODXL", "VCAN", "APOE")), name = "PE_markers")

data$Endo_character <- data$PE_markers1 - data$DE_markers1
data$Endo_bi <- ifelse(data$Endo_character > 0, "PE", "DE")

data$Cell.type <- factor(data$Cell.type, levels = annotation$order)

ggplot(data@meta.data, aes(x = Cell.type, y = Endo_character, fill = Cell.type)) + 
  geom_boxplot(outlier.shape = NA) + scale_fill_manual(values=as.character(annotation$colors), breaks = annotation$order) + theme_classic() + theme(axis.text.x = element_text(angle = 45, hjust=1)) + ylab("Relative Marker Expression") + xlab("Cell type") + geom_jitter(shape=".", position=position_jitter(0.2)) + ylim(-1.3, 2.7)
```

```{r Figure 4H}
require(Seurat)
require(dplyr)
require(slingshot)
require(scater)
require(SingleCellExperiment)

data <- readRDS("hee_seurat.rds") 

cluster_colors <- c("#85C1E9", "#B03A2E", "#F1948A", "#AF7AC5", "#F5B041", "#808B96", "#2471A3", "#229954")
cluster_order <- c("PI-Epi", "AME", "NNE", "PS-like", "Mesoderm-like", "G1 Hypoblast", "G2M/S Hypoblast", "AVE-like")

annotation <- data.frame(colors = cluster_colors, order = cluster_order)

ps_emt <- subset(data, idents = c("PS-like", "Mesoderm-like", "PI-Epi"))
ps_emt$Cell.type <- factor(ps_emt$Cell.type, levels = c("PI-Epi", "PS-like", "Mesoderm-like")) 

set.seed(42)
cells <- c(sample(colnames(subset(ps_emt, Cell.type == "PI-Epi")), size = (259+128), replace=F), colnames(subset(ps_emt, Cell.type == "PS-like" | Cell.type == "Mesoderm-like")))

d_ps_emt <- ps_emt[,cells]

d_ps_emt <- d_ps_emt %>% 
  NormalizeData() %>%
  FindVariableFeatures() %>%
  ScaleData() %>%
  RunPCA()

sce <- slingshot(as.matrix(d_ps_emt@reductions$pca@cell.embeddings), clusterLabels = d_ps_emt$Cell.type) 

colors <- rainbow(50, alpha = 1)
plot(reducedDim(sce), col = colors[cut(slingPseudotime(sce), breaks=50)], pch=16, asp = 1)
lines(sce, lwd = 2, type = 'curve', col = 'black')

sub_anno <- annotation[annotation$order %in% c("PS-like", "Mesoderm-like", "PI-Epi"),]

d_ps_emt$pseudotime_sling <- slingPseudotime(sce)

d_sce <- as.SingleCellExperiment(d_ps_emt)

plotExpression(d_sce, c("CDH1"), x = "pseudotime_sling", 
               colour_by = "Cell.type", show_violin = FALSE,
               show_smooth = TRUE) + scale_color_manual(values=as.character(sub_anno$colors), breaks = sub_anno$order)
plotExpression(d_sce, c("CDH2"), x = "pseudotime_sling", 
               colour_by = "Cell.type", show_violin = FALSE,
               show_smooth = TRUE) + scale_color_manual(values=as.character(sub_anno$colors), breaks = sub_anno$order) + xlab("Pseudotime")
plotExpression(d_sce, c("LHX1"), x = "pseudotime_sling", 
               colour_by = "Cell.type", show_violin = FALSE,
               show_smooth = TRUE) + scale_color_manual(values=as.character(sub_anno$colors), breaks = sub_anno$order)

```


















































